### PR TITLE
Multilingual examples

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@Androz2091

**Comment by Justman10000** [comment]
@Androz2091

**Comment by Androz2091** [comment]
We can't translate the readme in all the languages of the world I'm sorry. Thank you for your help though but we should keep English as the standard everyone use.

**Comment by Justman10000** [comment]
> We can't translate the readme in all the languages of the world I'm sorry. Thank you for your help though but we should keep English as the standard everyone use.

We could have just left German, couldn't we?

**Pull request closed without merging**
